version: '3'

services:
  kong-gw-db:
    image: postgres:13
    container_name: kong-gw-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    networks:
      - kong-network
    volumes:
      - ./Gateway/data:/var/lib/postgresql/data

  kong-gw:
    image: kong/kong-gateway:3.9.0.0
    container_name: kong-gw
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-gw-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_PATH: '/'
      KONG_ADMIN_GUI_URL: 'http://localhost:8002/manager'
    networks:
     - kong-network
    depends_on:
      - kong-gw-db

  gbear:
    container_name: gbear
    restart: always
    build:
      context: ./gbear
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Expose port 8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev # Optional, use if you want to activate the 'dev' profile
    networks:
     - kong-network
    depends_on:
      - rum
    
  rum:
    container_name: rum
    restart: always
    build:
      context: ./rum  # Path to the 'rum' directory
      dockerfile: Dockerfile  # Optional, as it's the default Dockerfile name
    ports:
      - "8081:8081"  # Adjust if your app uses a different port
    networks:
     - kong-network
    depends_on:
      - kong-gw

networks:
  kong-network:
    driver: bridge
    name: kong-network